# Config file for automatic testing at travis-ci.org

language: python

install:
    - pip install tox
env:
    - TOXENV=py27-django15
    - TOXENV=py27-django16
    - TOXENV=py27-django17
    - TOXENV=py27-django18
    - TOXENV=py34-django16
    - TOXENV=py34-django17
    - TOXENV=py34-django18

# command to run tests using coverage, e.g. python setup.py test
script: 
    - tox -e $TOXENV
    # - coverage run --source cursor_pagination runtests.py

# report coverage to coveralls.io
after_success: 
    - coveralls
